const CUSTOM_APP_CREATOR_GUIDE_LINES = [
  "# AI Phone Custom App Development Guide",
  "",
  "## 1. What This Is",
  "",
  "You are building a custom app for the \"AI Interactive Phone Simulator\" that users can install from the App Market. It can be a standalone shopping, check-in, SMS, food-delivery, forum, diary, toolbox, or any other kind of app.",
  "",
  "**Mental model**: an app is just a web page running inside the phone's sandboxed iframe. It **cannot** read the host's internal data directly. It can only request capabilities through the secure SDK the phone exposes (`window.AiPhone`) - read and write its own private data, read characters, have a character generate content, send cards into the chat, and so on.",
  "",
  "```",
  "┌───────────────── AI Phone Host ────────────────┐",
  "│  Characters / Memory / Chat History / Presets  │",
  "│        ▲ SDK request            │ callback     │",
  "│  ┌─────┴────────────────────────▼───────────┐  │",
  "│  │   Your APP (sandboxed iframe)            │  │",
  "│  │   index.html + manifest + declarations   │  │",
  "│  └──────────────────────────────────────────┘  │",
  "└────────────────────────────────────────────────┘",
  "```",
  "",
  "An app package is made of three kinds of things:",
  "",
  "* **Frontend**: `index.html` (required) plus static resources under `assets/`.",
  "* **manifest.json**: declares the app's identity, permissions, and extension entry points.",
  "* **Declaration files (optional)**: `presets.json`, which declares the prompt entries for the app's scenarios and hooks into the character generation pipeline.",
  "",
  "> Fastest way to validate: a single `index.html` is enough for a prototype. Add `manifest.json` and `icon.png` when you are ready to publish.",
  "",
  "---",
  "",
  "## 2. App Package Structure",
  "",
  "The user zips the finished package into a `.zip` and uploads it. Minimal structure:",
  "",
  "```txt",
  "my-app/",
  "├── manifest.json",
  "├── index.html",
  "├── icon.png",
  "└── assets/",
  "```",
  "",
  "More complex apps can put additional declaration files in the root directory. **Do not generate them unless you need them**; once you do, you must declare them in `manifest.resources`.",
  "",
  "|File|Responsibility (in one line)|",
  "|-|-|",
  "|`manifest.json`|App identity, permissions, extension entry points. Required for publishing|",
  "|`index.html`|Frontend entry point. Can stand alone while prototyping|",
  "|`icon.png`|App icon. Recommended (effectively required) for publishing|",
  "|`assets/`|Static resources: images, audio, fonts, etc.|",
  "|`presets.json` (optional; use it when characters inside your app need full global memory, calendar info, bound world books, etc.)|Prompt entries used to constrain what the character outputs and in what format. They enter the host's prompt preset management system, where the user can edit them.<br />That system already holds the character's complete information; once you call `AiPhone.ai.generate`, the preset entries your app defines are appended after it, and together they form the prompt.|",
  "",
  "> See [4.2 Declaration File JSON Format](#42-declaration-file-json-format) for how to write declaration files in detail.",
  "",
  "---",
  "",
  "## 3. manifest.json Field Reference",
  "",
  "`manifest.json` must be a JSON object. Full example:",
  "",
  "```json",
  "{",
  "  \"sdkVersion\": \"1.0\",",
  "  \"id\": \"waimai.demo\",",
  "  \"name\": \"Float Delivery\",",
  "  \"version\": \"1.0.0\",",
  "  \"author\": \"Your Name\",",
  "  \"description\": \"An app for browsing restaurants, picking dishes, and linking up with food-delivery cards in the chat.\",",
  "  \"icon\": \"icon.png\",",
  "  \"entry\": \"index.html\",",
  "  \"permissions\": [",
  "    \"app.data.read\",",
  "    \"app.data.write\",",
  "    \"characters.read\",",
  "    \"chat.sendCard\",",
  "    \"chat.requestReply\",",
  "    \"ai.generate\",",
  "    \"ui.toast\"",
  "  ],",
  "  \"resources\": {",
  "    \"presets\": [\"presets.json\"]",
  "  },",
  "  \"extensions\": {",
  "    \"chat\": {",
  "      \"directives\": [",
  "        {",
  "          \"id\": \"waimai-order\",",
  "          \"label\": \"Place Food Order\",",
  "          \"syntax\": \"[FoodOrder:recipient:restaurant:dish:note]\",",
  "          \"description\": \"Use this when the character wants to order food for the user and have the user confirm the order.\",",
  "          \"card\": {",
  "            \"appLabel\": \"Float Delivery\",",
  "            \"title\": \"Confirm Food Order\",",
  "            \"subtitle\": \"{{restaurant}}\",",
  "            \"body\": \"{{dish}} · {{note}}\",",
  "            \"status\": \"Pending\",",
  "            \"accentColor\": \"#f97316\",",
  "            \"sections\": [{",
  "              \"title\": \"Order Details\",",
  "              \"rows\": [",
  "                { \"label\": \"Recipient\", \"value\": \"{{recipient}}\" },",
  "                { \"label\": \"Restaurant\", \"value\": \"{{restaurant}}\" },",
  "                { \"label\": \"Dish\", \"value\": \"{{dish}}\" },",
  "                { \"label\": \"Note\", \"value\": \"{{note}}\" }",
  "              ]",
  "            }],",
  "            \"actions\": [{ \"label\": \"Confirm Order\" }]",
  "          }",
  "        }",
  "      ],",
  "      \"plusActions\": [",
  "        {",
  "          \"id\": \"order-food-for-character\",",
  "          \"label\": \"Order Food for Them\",",
  "          \"entry\": \"order-food-for-character\",",
  "          \"presentation\": \"panel\",",
  "          \"panelHeight\": \"72vh\",",
  "          \"description\": \"Opens the food-selection panel from the chat to order a meal for the current chat partner.\"",
  "        }",
  "      ]",
  "    }",
  "  }",
  "}",
  "```",
  "",
  "### 3.1 Top-Level Fields",
  "",
  "* **id**: an optional developer identifier. Letters, digits, dots, underscores, and hyphens only. Installation and market publishing generate their own internal app ID, so **the creator does not have to guarantee global uniqueness**.",
  "* **permissions**: declare only the capabilities you actually use (full list in [Section 6](#6-permission-list)). Add the matching permissions and fields on demand when you need external APIs, voice, tools, the wallet, or scheduled tasks.",
  "",
  "### 3.2 resources: Declare Only Files That Actually Exist in the Package",
  "",
  "Put static files such as images, audio, and fonts in `assets`. Omit an entry entirely if you have no files of that type:",
  "",
  "```json",
  "\"resources\": {",
  "  \"presets\": [\"presets.json\"],",
  "  \"assets\": [\"assets/menu-cover.png\"]",
  "}",
  "```",
  "",
  "* `assets` declares paths to static resources such as images, audio, and fonts. At runtime the app can call `AiPhone.app.getAssetUrl(\"assets/menu-cover.png\")` to get a usable URL.",
  "* If you need to register app tools, do not create a separate `tools.json` - put them directly in `manifest.extensions.tools`.",
  "* If the app has its own voice configuration, voice list, or notification sounds, put them in `assets` or in the app's private data and read them from the app itself.",
  "",
  "### 3.3 extensions (Optional)",
  "",
  "`extensions.chat` connects your app to the phone's most central app - the chat app. Rich media directives are actions the character can use; the built-in ones let a character do things like send a red envelope, share music, or send a sticker, and any new rich media directive you register here is appended to that list. The plus panel is the panel the user opens from the input bar; putting your app's actions there lets the user reach your custom app's features quickly from inside the chat app.",
  "",
  "> All of an app's chat extensions go under `extensions.chat.*`; all background event listeners go under `extensions.events`.",
  "",
  "#### extensions.chat.directives - Rich Media Directives",
  "",
  "This registers \"a piece of text markup the character can write directly into a chat reply\", shaped exactly as defined in `syntax` (for example `[FoodOrder:recipient:restaurant:dish:note]`). Rich media directives are how a custom app links up with the phone's chat app.",
  "",
  "* Once configured, the character receives a description of this available directive before it generates a reply.",
  "* When the character writes the directive in a reply, the host automatically renders the markup as your app's card and records it as a character action in the chat history the AI can see.",
  "* `card` is optional and customizes the card this directive is parsed into. Its fields use the same layout system as `AiPhone.chat.sendCard({ card })`: `title`, `subtitle`, `body`, `sections`, `actions`, `accentColor`, `html`, `height`, and so on.",
  "* Strings inside `card` can use directive argument placeholders: `{{arg1}}` and `{{1}}` by position, plus the names taken from `syntax` such as `{{recipient}}` and `{{restaurant}}`. If you omit `card`, the host's default card template is used.",
  "",
  "If your app wants more than a rendered card - for example, to sync data or run an action the moment the character emits the directive, such as a drift-bottle app automatically writing the bottle into its own database after the character outputs `[DriftBottle:content]` - you also need an event listener.",
  "",
  "How to do it:",
  "",
  "1. Declare the rich media directive in `extensions.chat.directives`. This tells the character the available format and lets the host render the output as a card.",
  "2. Declare a `chat.message.created` listener in `extensions.events`.",
  "3. In your app code, listen for new chat messages with `AiPhone.on(\"chat.message.created\", handler)`.",
  "4. In the handler, check whether the message came from the character and whether it contains your app's rich media directive. If it matches, the app decides for itself whether to write to its database, send a notification, update the card, or run some other action.",
  "",
  "If you want the listener to work even when the app is closed, set `background: true` in `extensions.events`.",
  "",
  "If you only need to handle things after the user taps the card, you do not need an event listener - just handle it once the card opens the app.",
  "",
  "#### extensions.chat.plusActions - Plus Panel Entries",
  "",
  "Registers app features in the plus panel of the user's chat.",
  "",
  "**presentation (display mode, defaults to `panel`)**:",
  "",
  "|Value|Effect|",
  "|-|-|",
  "|`panel`|Bottom sheet inside the chat (`panelHeight` only applies here)|",
  "|`modal`|Centered dialog inside the chat|",
  "|`fullscreen` / `app`|Opens the full app page|",
  "|`none`|No UI at all; only runs the app code|",
  "",
  "**Fields the app receives**: after the user taps, `AiPhone.app.getLaunchContext()` returns `source=\"chat_plus_action\"`, `sessionId`, `characterId`, `actionId`, `entry`, `data`, `directiveId`, `presentation`, and more. `entry` only tells the app which internal screen to render or which flow to run; the actual UI, the user interactions, the text written into the chat, and whether a character reply is triggered are all up to the app.",
  "",
  "**What you can do afterwards**: call `AiPhone.chat.sendCard` / `writeHistory` / `requestReply` to write back into the current chat, or `AiPhone.app.close()` to close the panel. If this entry point also needs to call the LLM, the app decides which tags that generation uses via `AiPhone.ai.generate({ appTags })`.",
  "",
  "**Common fields**: `id` (entry identifier), `label` (name shown in the panel), `entry` (internal screen identifier), `presentation`, `panelHeight`, `data` (custom JSON passed to the app), `directiveId` (links this entry to a rich media directive).",
  "",
  "#### extensions.tools - App Tools the Character Can Call",
  "",
  "App tools link your app with the phone's chat app. Once you declare real actions the character can invoke, the character can invoke them from inside the chat app. For example, a calendar app can register tools to edit, add, and delete events, so the character can drive your custom app from chat. Other people's custom apps can also link up with yours through tool calls.",
  "",
  "Tools are generally only for when you want the phone's chat app to interact with your custom app. For logic internal to your custom app you usually do not need tools, unless you specifically want the character to be able to call tools inside your app as well - for example, letting the character call MCP tools inside an SMS app.",
  "",
  "Every tool needs a `name`, a `description`, a parameter schema, and a `handler` name. In app code you implement the real action with `AiPhone.tools.handle(handlerName, fn)`. When a character calls one of your custom app's tools from the chat app and your app is not open, the host temporarily starts a hidden runtime to execute the same handler, then destroys it when it finishes. The hidden runtime is kept for at most 5 minutes by default; if you genuinely need longer, set `timeoutMs` in the tool declaration, up to a maximum of 30 minutes.",
  "",
  "* `visibility: \"private\"` → available only to generation inside this app; does not appear under Settings → Chat Toolbox.",
  "* `visibility: \"shared\"` → shared with regular chat and other apps; appears under Settings → Chat Toolbox.",
  "* Whether the character can actually see a tool is decided by `{{tools}}` in the preset entries carrying the same scenario tags. `{{tools}}` is a macro variable that injects the host's available tools and how to use them.",
  "",
  "See [5.11 Registering and Calling App Tools](#511-registering-and-calling-app-tools) for details and implementation.",
  "",
  "#### extensions.events - Listening to Host Events",
  "",
  "Declares which host events the app listens to at runtime. An array of objects is recommended:",
  "",
  "```json",
  "\"events\": [",
  "  {",
  "    \"event\": \"chat.message.created\",",
  "    \"entry\": \"events\",",
  "    \"background\": true,",
  "    \"description\": \"Listens for new chat messages. When background is true, the background handler runs temporarily even if the app is not open.\"",
  "  }",
  "]",
  "```",
  "",
  "* `event`: the event name. `entry`: your own internal entry name, handy for telling purposes apart. `background`: when `true`, the host may temporarily start a hidden runtime even while the app is closed and hand the event to your app's own `AiPhone.on` handler. `timeoutMs`: optional; only controls how long the hidden runtime is kept alive, defaulting to 5 minutes with a maximum of 30 minutes. `description`: documentation only.",
  "* The importer still accepts the `[\"chat.message.created\"]` string shorthand, but new packages should use the object form.",
  "",
  "---",
  "",
  "## 4. Declaration Files and the Character Generation Pipeline",
  "",
  "Declaration files feed the in-app character generation pipeline behind `AiPhone.ai.generate`. When the app calls `AiPhone.ai.generate({ characterId, appTags })`, the host selects the preset entries that should enter this generation based on the current character, the current app, and `appTags`.",
  "",
  "* `presets.json`: LLM prompt entries. They declare the character's output scenario and constrain the character to follow that scenario's rules and format.",
  "",
  "### 4.1 How Declaration Files Participate in `AiPhone.ai.generate`",
  "",
  "**How presets.json participates in the generation pipeline**:",
  "",
  "The phone hosts many apps, regular chats, games, and tools. So that every app can share the user persona, character persona, memory, and so on, the phone has a preset system. It contains **general entries and scenario entries**, and assembles them in the order defined by the preset system. In every app, anything that involves character output goes through the same preset prompt assembly pipeline, which keeps character settings, memory, calendar, and the rest consistent across apps.",
  "",
  "General entries include: character settings, character personality, user persona, core memory, long-term memory, the global event stream, world books, and more. These entries are usually placeholders that get replaced with the character's real content during assembly.",
  "",
  "Scenario entries include: the online chat output entry, the story mode output entry, the diary generation output entry, and so on. Scenario entries exist to control output format and make the AI understand the current scenario. For example, the Moments-post entry tells the character \"you are using the WeChat Moments feature\" and specifies an output format such as `[朋友圈]...[/朋友圈]`.",
  "",
  "So the final LLM prompt for posting to Moments is structured as: general entries (supplying the character's core persona, worldview, memory, etc.) plus scenario entries (making the AI understand the output scenario and format). The app then post-processes whatever the AI returns.",
  "",
  "The preset system is only used for character output pipelines. Without it, getting a character reply would mean fetching the character's full persona, world books, memory, calendar, user persona, and so on one item at a time, then appending your scenario prompt and sending it all to the LLM. The point of the preset system is that you only write one scenario entry - the character persona, world books, memory, user persona and the rest already live in the presets, so you never have to fetch and assemble them by hand. Call `AiPhone.ai.generate` with the `appTags` of the scenario preset you wrote, and the character automatically picks up the full persona, memory, and so on, then outputs according to that scenario's rules and format.",
  "",
  "**How presets.json chooses tags**: to use different scenario entries in different situations without letting them bleed into each other, we distinguish scenario entries by tags. For example, a Moments-post scenario preset could use `['moments', 'post']`, and an SMS reply scenario preset could use `['sms', 'reply']`.",
  "",
  "Each prompt entry can carry a set of tags. Once `appTags` is passed for a generation, only entries whose tags are a subset of that generation's `appTags` enter the prompt. The host's built-in general entries usually have no tags, so they enter every applicable pipeline. Entries in an app's own `presets.json` usually should have tags.",
  "",
  "In other words: every tag an entry requires must appear in this generation's `appTags`.",
  "",
  "Example (this generation has `appTags = [\"sms\", \"reply\"]`):",
  "",
  "|Entry tags|Enters?|Why|",
  "|-|-|-|",
  "|none|✅|General entry, not filtered by scenario|",
  "|`[\"sms\"]`|✅|Subset of appTags|",
  "|`[\"sms\", \"reply\"]`|✅|Both tags are present in appTags|",
  "|`[\"sms\", \"proactive\"]`|❌|`proactive` is not in this generation's appTags|",
  "",
  "**Conventions for writing presets.json tags**:",
  "",
  "* Must be an array of English strings. `[main feature, sub-scenario]` is recommended, e.g. `[\"sms\", \"reply\"]`, `[\"sms\", \"proactive\"]`, `[\"dungeon\", \"scene\"]`.",
  "* Tags are used for scenario filtering, so use stable English scenario identifiers.",
  "* Rich media directives (`directives`) and plus panel entries (`plusActions`) do not rely on this tag filtering. They identify features with `entry`, `directiveId`, and `data`. Only presets and `AiPhone.ai.generate({ appTags })` need to match strictly by the rules above.",
  "",
  "An SMS app has two scenarios that need the character to generate text:",
  "",
  "|Scenario|appTags|Purpose|",
  "|-|-|-|",
  "|SMS reply|`[\"sms\", \"reply\"]`|The user texts the character from the SMS app, and the character replies based on the message and the relationship context|",
  "|Proactive SMS|`[\"sms\", \"proactive\"]`|Based on some event, time, or state, the app has the character text the user first|",
  "",
  "Correspondingly, `presets.json` can hold two presets, tagged with those two sets:",
  "",
  "* The \"SMS reply\" preset: constrain the character to reply in a texting voice, keep it short and message-like, and specify an output format the frontend can parse.",
  "* The \"Proactive SMS\" preset: constrain the character to have a clear motive when reaching out first, avoid rambling on the way a normal chat would, and specify an output format the frontend can parse.",
  "",
  "When the app calls `AiPhone.ai.generate` with `appTags: [\"sms\", \"reply\"]`, the prompt is the general entries plus the \"SMS reply\" preset; with `appTags: [\"sms\", \"proactive\"]`, it is the general entries plus the \"Proactive SMS\" preset.",
  "",
  "**Output post-processing**: `ai.generate` only returns text. If your preset told the character to output some fixed markup (such as `[Status:location=...;time=...]`), the app simply parses `result.text` in its own JS and renders it as a card or a status bar - there is no need to register any rule with the host.",
  "",
  "**World books**: world books configured in the character's binding settings automatically enter the generation pipeline, and the app does not have to do anything. Write your app's own scenario background directly into the preset entries.",
  "",
  "### 4.2 Declaration File JSON Format",
  "",
  "#### presets.json Minimal Structure",
  "",
  "Every preset is an LLM prompt entry that constrains the content, tone, and format of what the character outputs inside the current app.",
  "",
  "```json",
  "{",
  "  \"presets\": [",
  "    {",
  "      \"id\": \"sms-reply-style\",",
  "      \"name\": \"SMS Reply\",",
  "      \"content\": \"You are replying to the user in an SMS app. Write one natural text message in character. Keep it shorter than a normal chat message and make it read like a real phone text. The output format is fixed: [SmsReply:content].\",",
  "      \"enabled\": true,",
  "      \"tags\": [\"sms\", \"reply\"]",
  "    },",
  "    {",
  "      \"id\": \"sms-proactive-style\",",
  "      \"name\": \"Proactive SMS\",",
  "      \"content\": \"You are texting the user first from an SMS app. You must have a clear motive. Keep it short and natural, and do not keep asking follow-up questions the way a normal chat would. The output format is fixed: [ProactiveSms:content].\",",
  "      \"enabled\": true,",
  "      \"tags\": [\"sms\", \"proactive\"]",
  "    }",
  "  ]",
  "}",
  "```",
  "",
  "---",
  "## 5. SDK Reference",
  "",
  "### 5.1 Entry Point and Conventions",
  "",
  "```js",
  "const api = window.AiPhone;        // main entry point",
  "// const api = window.AiPhoneApp;  // the host also accepts this alias",
  "```",
  "",
  "Every API is an async Promise.",
  "",
  "### 5.2 Quick Reference (Capability → Method → Required Permission)",
  "",
  "|Capability|Main methods|Required permission|",
  "|-|-|-|",
  "|Read app info|`app.getManifest` / `getCapabilities` / `getLaunchContext` / `close`|none|",
  "|Private database|`db.create` / `list` / `get` / `update` / `delete`|`app.data.read` / `app.data.write`|",
  "|Read characters|`characters.list` / `get` / `readState` / `writeState` / `readRelations`|`characters.read` / `characters.state.*` / `characters.relations.read`|",
  "|User profile|`user.getProfile` / `getPersona` / `getPreferences`|`user.profile.read` / `user.persona.read` / `user.preferences.read`|",
  "|External API|`network.fetch`|`network.fetch` (+ manifest `network.allowedDomains`)|",
  "|Character text generation|`ai.generate`|`ai.generate`|",
  "|AI image generation|`ai.generateImage`|`ai.generateImage`|",
  "|General-purpose models|`ai.chat` / `ai.embed` / `ai.classify`|`ai.chat` / `ai.embed` / `ai.classify`|",
  "|Voice|`voice.readProfiles` / `tts` / `stt` / `clone`|`voice.readProfiles` / `voice.tts` / `voice.stt` / `voice.clone`|",
  "|Audio playback (host-proxied)|`voice.play` / `stopPlayback` / `pausePlayback` / `resumePlayback`|`voice.tts`|",
  "|Calendar|`calendar.read` / `create` / `update` / `write`|`calendar.read` / `calendar.write`|",
  "|World books|`world.list` / `get` / `read`|`world.read`|",
  "|Media|`media.pick` / `save`|`media.pick` / `media.save`|",
  "|Geolocation (host-proxied)|`geo.get` / `geo.watch` / `geo.clearWatch` + `AiPhone.on(\"geo.position\", …)`|`geo.read` / `geo.watch` (continuous position events must be declared as `geo.position` in the manifest)|",
  "|Media store (large files)|`media.put` / `get` / `delete`|`app.data.write` / `app.data.read`|",
  "|App tools|`tools.handle` / `invoke`|`chat.tools`|",
  "|Send/update cards|`chat.sendCard` / `updateCard`|`chat.sendCard` (or `chat.write`)|",
  "|Write chat history|`chat.writeHistory`|`chat.write` or `chat.sendMessage`|",
  "|Request a character reply|`chat.requestReply`|`chat.requestReply`|",
  "|Open a chat|`chat.openConversation`|—|",
  "|Contact state|`chat.setContactState` / `unblock` / `unmute`|`chat.contacts.write`|",
  "|Read chat history|`chat.getCurrentSession` / `readHistory`|`chat.read`|",
  "|Listen for events|`AiPhone.on(\"chat.message.created\", …)`|`chat.read` or `chat.read.background` (+ declare the event in the manifest)|",
  "|Read memory|`memory.readCore` / `readLongTerm` / `readShortTerm` / `search`|`memory.read*` / `memory.search`|",
  "|Write memory|`memory.add` / `addTimeline`|`memory.write`|",
  "|Suggest memory|`memory.suggest`|`memory.suggest`|",
  "|UI prompts|`ui.toast` / `showNotification` / `confirm`|`ui.toast` / `ui.notification`|",
  "|Notifications/badges|`notifications.create` / `getBadge` / `setBadge` / `clearBadge` / `list` / `markAllRead`|`notifications.read` / `notifications.write`|",
  "|Scheduled tasks|`tasks.schedule`|`tasks.schedule` (+ each action's own permission)|",
  "|Wallet|`wallet.get` / `pay`|`wallet.read` / `wallet.pay`|",
  "|Multiplayer (see 5.25)|`room.create` / `join` / `send` / `setState` / `kick` + `cloud.put` / `list` / `takeRandom` + `AiPhone.on(\"room.*\", …)`|`online.play` (room events must be declared in the manifest)|",
  "",
  "### 5.3 Reading App Info",
  "",
  "```js",
  "const manifest = await AiPhone.app.getManifest();",
  "const capabilities = await AiPhone.app.getCapabilities();",
  "const launchContext = await AiPhone.app.getLaunchContext();",
  "await AiPhone.app.close();",
  "```",
  "",
  "`launchContext` depends on how the app was opened:",
  "",
  "* Opened from a rich media card in chat: includes `source`, `messageId`, `sessionId`, `directiveId`, `directiveLabel`, `directiveArgs`, `directiveRaw`, `summary`, and more.",
  "* Opened from the plus panel: includes `source=\"chat_plus_action\"`, `sessionId`, `characterId`, `actionId`, `entry`, `data`, `appTags`, `presentation`, and more.",
  "* Opened normally from the home screen: usually `null`.",
  "",
  "### 5.4 Private Database",
  "",
  "This data belongs only to the current app. It is cleared only if the user chooses to delete data while uninstalling the app.",
  "",
  "```js",
  "const item = await AiPhone.db.create(\"orders\", { title: \"Tom Yum Soup\", status: \"draft\" });",
  "// Note: do not store large files such as audio/images as dataURLs in a record; swap them for a reference with media.put first (see 5.10)",
  "const list = await AiPhone.db.list(\"orders\", { limit: 100 });",
  "const one  = await AiPhone.db.get(\"orders\", item.id);",
  "await AiPhone.db.update(\"orders\", item.id, { status: \"paid\" });",
  "await AiPhone.db.delete(\"orders\", item.id);",
  "```",
  "",
  "Create / list / get / update / delete are provided, but **there is no upsert**. To save settings, `list` first to find an existing record id and `update` it; if there is none, `create` it.",
  "",
  "### 5.5 Reading Characters",
  "",
  "Many chat APIs need a `characterId`. It is a good idea to write a \"get the current character\" helper first: when opened from a card or the plus panel, prefer `launchContext.characterId`; when opened from the home screen, use `characters.list()` to build a character picker and save the user's choice as `selectedCharacterId`.",
  "",
  "```js",
  "const launchContext = await AiPhone.app.getLaunchContext();",
  "const characters = await AiPhone.characters.list();",
  "const selectedCharacterId = launchContext?.characterId || characters[0]?.id;",
  "if (!selectedCharacterId) throw new Error(\"Please create or select a character first\");",
  "",
  "const character = await AiPhone.characters.get(selectedCharacterId);",
  "const state = await AiPhone.characters.readState({ characterId: selectedCharacterId });",
  "const relations = await AiPhone.characters.readRelations({ characterId: selectedCharacterId });",
  "await AiPhone.characters.writeState({",
  "  characterId: selectedCharacterId,",
  "  stateValues: [{ name: \"Affection\", value: 72 }]",
  "});",
  "```",
  "",
  "`list`/`get` need `characters.read`; `readState`/`writeState` need `characters.state.read`/`characters.state.write`; `readRelations` needs `characters.relations.read`.",
  "",
  "### 5.6 Reading User Profile and Persona",
  "",
  "The user profile and persona are the user's mask - the role the user plays in chats and story interactions. If you assemble the prompt yourself instead of using `AiPhone.ai.generate`, you must pass the user profile and persona in, otherwise the character will not know who the user is playing.",
  "",
  "```js",
  "const profile = await AiPhone.user.getProfile({ characterId: selectedCharacterId });",
  "const persona = await AiPhone.user.getPersona({ characterId: selectedCharacterId });",
  "const preferences = await AiPhone.user.getPreferences({ characterId: selectedCharacterId });",
  "console.log(profile.name, persona.text, preferences.text);",
  "```",
  "",
  "These need `user.profile.read` / `user.persona.read` / `user.preferences.read` respectively.",
  "",
  "### 5.7 Calling External APIs",
  "",
  "You can only reach domains declared in the manifest's `network.allowedDomains`. Exact domains and `*.example.com` wildcard subdomains are supported; localhost and intranet addresses are **not allowed**.",
  "",
  "By default `AiPhone.network.fetch` connects to the target API directly from the browser client, which does not consume the site's server-side function quota. If the target API does not enable CORS, the direct connection fails; only when you genuinely need a server-side proxy should you pass `proxy: true` on a single request or set `network.mode: \"proxy\"` in the manifest. `timeoutMs` is optional - if omitted, the host does not cut the request off; if provided, it affects only that request. When going through the proxy, `timeoutMs` cannot exceed the 120-second guard on `/api/tool-proxy`.",
  "",
  "```js",
  "const response = await AiPhone.network.fetch({",
  "  url: \"https://api.example.com/orders\",",
  "  method: \"POST\",",
  "  headers: { \"Content-Type\": \"application/json\" },",
  "  body: { dish: \"Tom Yum Soup\", count: 1 },",
  "  timeoutMs: 30000",
  "});",
  "if (response.ok) console.log(response.json || response.text);",
  "```",
  "",
  "```js",
  "// Only write it this way when the target API cannot be reached directly from the browser and you accept going through the site's server proxy",
  "const response = await AiPhone.network.fetch({",
  "  url: \"https://api.example.com/orders\",",
  "  method: \"POST\",",
  "  body: { dish: \"Tom Yum Soup\", count: 1 },",
  "  proxy: true,",
  "  timeoutMs: 60000",
  "});",
  "```",
  "",
  "Needs `network.fetch`, and the manifest must declare `network.allowedDomains`.",
  "",
  "### 5.8 Having a Character Generate Text",
  "",
  "`ai.generate` assembles one **complete prompt** for the specified character, but only returns text - it does not post to the chat automatically. It preserves the base context: character persona, user persona, core memory, long-term memory, the short-term memory event stream, and so on. When you pass `appTags`, matching app preset entries are added as well (rules in [Section 4](#4-declaration-files-and-the-character-generation-pipeline)).",
  "",
  "For a simple single-turn task, pass only `instruction`. If your app keeps its own internal records - a multi-turn story, an SMS thread, a support conversation - pass those records as `messages`. The host treats `messages` as real `user` / `assistant` history participating in the unified prompt assembly, rather than cramming them into a single block of explanatory text.",
  "",
  "`messages` is your app's own private multi-turn history. The short-term memory event stream is read separately by the host and contains the character's recent chats, group chats, events from other apps, diary entries, Moments posts, and so on. When building the final prompt, the host merges the short-term memory event stream and `messages`, sorts them by `createdAt` / `timestamp`, and places them inside `<shortTermMemory>`. So a multi-turn app should preserve the `createdAt` of every message it stores.",
  "",
  "```js",
  "const scene = await AiPhone.db.get(\"scenes\", sceneId);",
  "const turns = scene.turns || [];",
  "",
  "const result = await AiPhone.ai.generate({",
  "  characterId: selectedCharacterId,",
  "  appTags: [\"infinite_flow\", \"scene\"],",
  "  messages: turns.slice(-24).map(turn => ({",
  "    role: turn.role,",
  "    content: turn.content,",
  "    createdAt: turn.createdAt",
  "  })),",
  "  instruction: `",
  "Current instance summary:",
  "${scene.summary || \"none yet\"}",
  "",
  "Current scene state:",
  "${JSON.stringify(scene.state || {}, null, 2)}",
  "",
  "The user's action this turn:",
  "${userAction}",
  "",
  "Continue the story as the current character. Output only the character's reply for this turn.",
  "`",
  "});",
  "console.log(result.text);",
  "",
  "await AiPhone.db.update(\"scenes\", sceneId, {",
  "  turns: [",
  "    ...turns,",
  "    { role: \"user\", content: userAction, createdAt: new Date().toISOString() },",
  "    ...result.appendMessages",
  "  ]",
  "});",
  "```",
  "",
  "* `messages` / `appMessages`: the multi-turn record your app maintains. Supports `role: \"user\" | \"assistant\" | \"system\" | \"tool\"`, `content`, and `createdAt`, plus tool context fields such as `mediaType`, `rawResponseText`, `nativeToolCalls`, and `nativeToolResult`. Omitting it means this app has no private multi-turn history; the host still fills in the character's recent chats and other app events through the short-term memory event stream.",
  "* A message can carry an `image` (a `data:image/...` dataURL) to let the character \"see\" a picture through the vision channel: at most 4 images per generation, each dataURL under 2MB - send compressed thumbnails. If the user's model does not support image recognition or has it disabled, the image automatically degrades to the literal text `[图片]` (\"[image]\"), and the app does not need to check for this. Your prompt should say something like \"do not invent details when you cannot see the image content\".",
  "* `instruction`: the task description for this turn. Good for the current state, what the user just did, and the output requirements. Do not stuff dozens of turns of history into `instruction` - multi-turn history belongs in `messages`.",
  "* `result.text`: the final displayable reply text after this turn's tool loop finishes.",
  "* `result.appendMessages`: the context messages this generation added, including intermediate tool calls, tool results, and the final assistant reply. A story app should append them to its own multi-turn record and pass them back unchanged as `messages` on the next turn. Text-protocol tool results are stored as `role: \"user\"` + `mediaType: \"tool_result\"`; native tool results are stored as `role: \"tool\"` + `nativeToolResult`.",
  "* `historyLimit`: optional. When the generation profile uses `history: \"recent\"`, it limits `messages` / `appMessages` to the most recent N entries. Usually the app decides how many turns of history to send.",
  "",
  "**Multi-character generation**: replace `characterId` with a `characterIds` array (or pass the `sessionId` of an existing group chat) to put several characters on stage in a single generation. The mental model is identical to the single-character case: the host assembles a \"multi-character info pack\" (every character's full persona, state, memory, calendar, and world books enter the context), and the scenario task comes from your `presets.json` entries matched by `appTags` - the host does not mix in its own built-in chat/group-chat format entries. **The output format is entirely up to your scenario entries; raw text is returned and the app parses and renders it itself** (if you want to know who said which line, define a line-marker format in the preset).",
  "",
  "```js",
  "const result = await AiPhone.ai.generate({",
  "  characterIds: [\"char_a\", \"char_b\", \"char_c\"],",
  "  appTags: [\"theater\", \"scene\"],",
  "  instruction: \"The three of them face off on the rooftop. Push this scene forward per the script; everyone speaks at least once.\"",
  "});",
  "// result.text is the model's raw output; parse it yourself using the format you defined in the preset",
  "const lines = result.text.match(/\\[Line@[^\\]]+\\]/g);",
  "```",
  "",
  "* `characterIds`: the array of character ids taking part in the generation. You can pass `sessionId` instead (an existing group chat session), in which case that group's recent chat history is automatically pulled in as context.",
  "* `result.text`: the model's raw output text. The host does not split it by character or clean up the format in any way.",
  "* `result.appendMessages`: same as single-character mode; pass it back as `messages` to continue a multi-turn exchange.",
  "* Multi-character mode also supports `messages`, `instruction`, `appTags`, `historyLimit`, and generation profiles; tool calls are not supported yet.",
  "",
  "Needs `ai.generate`.",
  "",
  "When you do not need the character chat pipeline and just want to call a general-purpose model, use `ai.chat` / `ai.embed` / `ai.classify`:",
  "",
  "```js",
  "const chat = await AiPhone.ai.chat({",
  "  messages: [",
  "    { role: \"system\", content: \"You are a terse classification assistant.\" },",
  "    { role: \"user\", content: \"Does this comment read like a negative review?\" }",
  "  ],",
  "  timeoutMs: 60000",
  "});",
  "const embedding = await AiPhone.ai.embed({ text: \"The tom yum soup is delicious\" });",
  "const cls = await AiPhone.ai.classify({ text: \"Way too spicy\", labels: [\"positive\", \"neutral\", \"negative\"] });",
  "```",
  "",
  "`timeoutMs` on `ai.chat` is optional - if omitted, the host does not cut the request off; if provided, it affects only that request. These need `ai.chat` / `ai.embed` / `ai.classify` respectively.",
  "",
  "When you need an illustration, use `ai.generateImage`. It reuses the image-generation API the user configured in the host settings, so the app does not have to manage an image API key of its own:",
  "",
  "```js",
  "const image = await AiPhone.ai.generateImage({",
  "  prompt: \"A warm illustration of a late-night convenience store on a street corner, warm yellow light, wet pavement reflecting after rain\",",
  "  characterId: selectedCharacterId,",
  "  useReferenceImage: true",
  "});",
  "if (image.dataUrl) imgEl.src = image.dataUrl;",
  "```",
  "",
  "* `prompt`: the image description; required. With `characterId` + `useReferenceImage: true`, the reference image configured for that character in the host settings is included so the person in the picture looks closer to the character. Without `useReferenceImage`, or if the character has no reference image, generation is based on the text description alone.",
  "* Returns `{ ok, dataUrl, mimeType, prompt, revisedPrompt?, usedReferenceImage }`; `dataUrl` can be used directly in `<img src>`.",
  "* **To keep a generated image long-term, swap it for a reference with `media.put` before storing it in the db** (see 5.10). Do not stuff the raw `dataUrl` into `db.create/update` - a few images is a few MB, which makes the store slow and crash-prone.",
  "* If the user has not configured or enabled an image-generation API in the host settings, this throws. Wrap it in `try/catch` and tell the user to configure it in settings; do not assume image generation always succeeds.",
  "* Image generation is usually slower than text generation (10-30 seconds is common), so show a waiting state in the UI. Pass `timeoutMs` if you need a longer limit.",
  "* Needs `ai.generateImage`.",
  "",
  "### 5.9 Voice Capabilities",
  "",
  "```js",
  "const voices = await AiPhone.voice.readProfiles({ characterId: selectedCharacterId });",
  "const speech = await AiPhone.voice.tts({ characterId: selectedCharacterId, text: \"Your delivery is here.\" });",
  "// Playback must go through the host; do not call new Audio() or use Web Audio yourself (reasons below)",
  "await AiPhone.voice.play({ dataUrl: speech.dataUrl });  // resolves only after playback finishes",
  "const stt = await AiPhone.voice.stt({ lang: \"en-US\", timeoutMs: 15000 });",
  "",
  "const pickedAudio = await AiPhone.media.pick({ accept: \"audio/*\" });",
  "const cloned = await AiPhone.voice.clone({",
  "  voiceConfigId: voices.selected?.id,",
  "  voiceId: \"waimai_voice_001\",",
  "  name: \"Delivery Alert Voice\",",
  "  audioDataUrl: pickedAudio.file.dataUrl",
  "});",
  "```",
  "",
  "`readProfiles`/`tts`/`stt`/`clone` need `voice.readProfiles`/`voice.tts`/`voice.stt`/`voice.clone` respectively. The `clone` example above uses `media.pick` to choose an audio file, so it also needs `media.pick`. `clone` currently uses the Minimax cloning API.",
  "",
  "**Always play through `voice.play` (host-proxied); never build your own `<audio>` element or Web Audio inside the app**: the app runs in a sandboxed iframe, so a self-built `<audio>` binds the iOS lock-screen media card to a blank address that cannot be opened (one tap and the whole app goes white), and Web Audio gets silenced entirely by the iOS mute switch. `voice.play` plays through a media element on the host page, which avoids both pitfalls.",
  "",
  "```js",
  "await AiPhone.voice.play({ dataUrl: speech.dataUrl });            // main channel, resolves when done",
  "AiPhone.voice.play({ channel: \"ambience\", dataUrl: bgmDataUrl, loop: true, volume: 0.3 }); // looping ambience",
  "await AiPhone.voice.stopPlayback({ channel: \"voice\" });          // stop",
  "await AiPhone.voice.pausePlayback({});                             // pause (voice channel by default)",
  "await AiPhone.voice.resumePlayback({});                            // resume",
  "```",
  "",
  "* Two channels: `voice` (default, for lines and alert sounds) and `ambience` (looping background audio). They never interrupt each other; a new playback on the same channel replaces the old one.",
  "* `dataUrl` can also be a `media-store://` reference returned by `media.put` (recommended, see 5.10), in which case the audio data never crosses the message bridge at all.",
  "* Playback needs the `voice.tts` permission. It rejects when the browser blocks playback, so `try/catch` and fall back to text.",
  "",
  "`voice.tts` optionally takes `emotion` (Minimax only; one of `happy`/`sad`/`angry`/`fearful`/`disgusted`/`surprised`/`calm`/`neutral`/`fluent`, invalid values are ignored) to control the emotion of the whole line. Whether a voice supports this field, or supports the more advanced inline tags (such as `(laughs)`, `(sighs)`, `(breath)` - only Minimax `speech-2.8-hd`/`speech-2.8-turbo` support these; other models and providers will read them aloud as literal English), is something you should determine yourself by reading `selected.provider`/`selected.model` via `voice.readProfiles`. Do not blindly assume every voice configuration supports it.",
  "",
  "**Return shapes**:",
  "",
  "* `voice.tts` → `{ ok, configId, provider, voiceId, mimeType, size, dataUrl }`; `dataUrl` can be played directly.",
  "* `voice.stt` → `{ ok, text, interim?, reason? }`.",
  "* `voice.readProfiles` → `{ selected, profiles, characterId? }`; each profile includes `provider`/`model`, which you can use to work out which advanced capabilities the current voice supports.",
  "",
  "### 5.10 Calendar, World Books, and Media",
  "",
  "```js",
  "const week = await AiPhone.calendar.read({ ownerType: \"character\", ownerId: selectedCharacterId });",
  "await AiPhone.calendar.create({",
  "  ownerType: \"character\", ownerId: selectedCharacterId,",
  "  date: \"2026-06-25\", startTime: \"18:30\", endTime: \"19:00\",",
  "  title: \"Wait for delivery\", location: \"Home\"",
  "});",
  "",
  "const world = await AiPhone.world.list({ query: \"major story event\" });",
  "",
  "const picked = await AiPhone.media.pick({ accept: \"image/*\" });",
  "const saved = await AiPhone.media.save({ dataUrl: picked.file.dataUrl, type: \"custom_app_media\" });",
  "```",
  "",
  "Calendar needs `calendar.read`/`calendar.write`; world books need `world.read`; media needs `media.pick`/`media.save`.",
  "",
  "#### Media Store: The Right Way to Store Large Files",
  "",
  "**Do not store large files such as audio and images as dataURLs inside `db.*` records.** A db record is serialized as one blob of text, so if you push a few voice clips into it, every small edit afterwards has to re-serialize tens of MB - slow, memory-hungry, and capable of crashing the whole app on iOS. The right approach is to swap them for a reference with `media.put` and store only the reference string in the db:",
  "",
  "```js",
  "// Store: dataURL → reference (Blob written to disk, not held in memory)",
  "const stored = await AiPhone.media.put({ dataUrl: speech.dataUrl });",
  "await AiPhone.db.create(\"clips\", { title: \"Good night\", audioRef: stored.ref });",
  "",
  "// Play: hand the reference straight to the host; audio data never crosses the message bridge",
  "await AiPhone.voice.play({ dataUrl: clip.audioRef });",
  "",
  "// Show an image: turn the reference back into a dataURL (blob objectURLs are blocked by same-origin rules inside the sandboxed iframe, do not use them)",
  "const img = await AiPhone.media.get({ ref: item.coverRef });",
  "coverEl.src = img.dataUrl;",
  "",
  "// Delete: when deleting a record, delete the media it references too so nothing is left behind",
  "await AiPhone.media.delete({ ref: item.coverRef });",
  "```",
  "",
  "* `media.put({ dataUrl })` → `{ ref, mime, category }`, where `ref` looks like `media-store://...`; 25MB per item. Needs `app.data.write`.",
  "* `media.get({ ref })` → `{ ref, mime, dataUrl }`. The dataURL can be used directly in `<img src>`, CSS backgrounds, or exports. Needs `app.data.read`. You can only read media your own app stored. Fetch on demand rather than preloading the whole library - only the images currently on screen should occupy memory.",
  "* `media.delete({ ref })` deletes the media itself; when you delete a db record, remember to delete the media it references. When the app is uninstalled with data cleared, the host removes all its media automatically.",
  "",
  "**Calendar fields**:",
  "",
  "* `calendar.read({ ownerType, ownerId/characterId, weekStart/date, includeAll })` → `{ ownerType, ownerId, weekStart, plan, plans? }`, where `plan.items` is the array of events for the week.",
  "* `calendar.create/update/write` for a single event requires `date`, `startTime`, `endTime`, and `title`. `date` is `YYYY-MM-DD` and `startTime`/`endTime` are `HH:MM`. `id`, `location`, and `source` are optional.",
  "* `calendar.write({ operation: \"replace\", items: [...] })` replaces the whole week; with `operation: \"delete\"`, pass `itemId` or `id`.",
  "",
  "**World book fields**:",
  "",
  "* `world.list({ query, includeEntries })` → `{ books: [...] }`; `world.get(id)` or `world.read({ id })` → `{ book }`.",
  "* Common world book fields: `id`, `name`, `description`, `entries`, `entryCount`, `createdAt`, `updatedAt`.",
  "* Common entry fields: `key`, `content`, `comment`.",
  "* World books are read-only to apps: the world books bound to a character automatically enter the `ai.generate` pipeline with no involvement from the app. Put your app's own scenario background in `presets.json` entries instead.",
  "",
  "### 5.10.1 Geolocation (Host-Proxied)",
  "",
  "The app's sandboxed iframe is an opaque origin, so `navigator.geolocation` can never obtain permission. Geolocation is therefore proxied by the host page (same reasoning as `voice.play`). Coordinates are WGS-84; to display them on Chinese map providers such as Amap, the app must convert to GCJ-02 itself.",
  "",
  "```js",
  "// One-shot position (needs geo.read)",
  "const pos = await AiPhone.geo.get({ timeoutMs: 10000 });",
  "console.log(pos.lat, pos.lng, pos.accuracy);",
  "",
  "// Continuous tracking (needs geo.watch; the events must be declared as geo.position / geo.error in manifest extensions.events)",
  "AiPhone.on(\"geo.position\", p => updateMyDot(p.lat, p.lng));",
  "AiPhone.on(\"geo.error\", e => console.warn(e.message));",
  "await AiPhone.geo.watch({});",
  "// Always stop it when you are done:",
  "await AiPhone.geo.clearWatch();",
  "```",
  "",
  "The first call triggers the browser's location permission prompt. If the user denies it, `geo.get` rejects and watch emits a `geo.error` event, so the app must be ready to degrade gracefully (manual pin placement, etc.). Continuous tracking only works while the app is open; the host stops listening automatically when the runner closes.",
  "",
  "### 5.11 Registering and Calling App Tools",
  "",
  "The phone has a unified chat toolbox, found under Settings → Chat Toolbox. The toolbox lets a character perform real actions during a chat or an app generation - calling an external REST API, calling an MCP service, running a composite tool, using the phone's internal capabilities, or linking up with other apps on the phone. For example, a music tool lets the character control the music app from chat; a custom food-delivery app can register tools like \"order food\" and \"submit a delivery review\" for the character to call.",
  "",
  "Tools are not \"another way to write a prompt\". If the character only needs to write a sentence, polish some content, judge a mood, or draft a review, use preset entries and `AiPhone.ai.generate` instead - do not declare a tool. Tools are only for real actions: reading and writing state, calling APIs, creating orders, submitting reviews, controlling other apps.",
  "",
  "The toolbox uses two-level lazy loading:",
  "",
  "* A single tool is exposed to the character directly.",
  "* Multiple tools are first exposed as one \"tool suite / meta tool\"; when the character needs it, it expands the suite and then calls a specific sub-tool.",
  "* REST tool suites, composite tool suites, MCP services, and multi-tool declarations from custom apps all follow this pattern.",
  "* This avoids stuffing a large pile of tool schemas into the prompt at once - the character only fetches the specific action description when it needs it.",
  "",
  "A custom app plugs into the toolbox by declaring a set of app tools in the manifest's `extensions.tools`. Once the app is installed, tools with `visibility: \"shared\"` become part of the chat toolbox, and they are removed along with the app when it is uninstalled. When an app declares exactly one shared tool, it appears as a single tool; when the same app declares several, they appear as \"that app's tool suite\", with the sub-tools visible after expanding it. Tools with `visibility: \"private\"` are for internal use by that app only and do not appear in the chat toolbox.",
  "",
  "Whether the character sees an app tool is decided by permissions, `visibility`, and `{{tools}}` together:",
  "",
  "* `permissions` must include `chat.tools`.",
  "* `visibility: \"private\"`: only the owning app's own `AiPhone.ai.generate` pipeline can see the tool.",
  "* `visibility: \"shared\"`: the owning app, regular chat, and other apps' generation pipelines can all see the tool. It also appears under Settings → Chat Toolbox, where the user can enable or disable it globally.",
  "* The preset entries in the current generation pipeline must contain `{{tools}}`, otherwise the tools are never handed to the model. Without `{{tools}}`, the model sees neither the tool descriptions nor the native tool schema, even if the manifest declares tools.",
  "",
  "When a tool runs, the host prefers to reuse the handler of an already-open app. If the app is not open, it temporarily starts a hidden runtime, waits for the app to register a handler of the same name via `AiPhone.tools.handle(handlerName, fn)`, and then passes the tool arguments to it. Async reads and writes, network requests, and chat writes inside the handler must be `await`ed or returned as a Promise, otherwise the hidden runtime may shut down early. The hidden runtime is kept for at most 5 minutes by default; if you genuinely need longer, set `timeoutMs` in the tool declaration, up to a maximum of 30 minutes. `actions` / `resultTemplate` can serve as a declarative fallback for very simple tools, but they are not the required path - when you need real logic such as reading and writing app private data, submitting an order, or writing a review, write a handler.",
  "",
  "Declaring a set of tools in the manifest:",
  "",
  "```json",
  "{",
  "  \"permissions\": [\"chat.tools\", \"app.data.write\"],",
  "  \"extensions\": {",
  "    \"tools\": [",
  "      {",
  "        \"id\": \"submit-takeout-review\",",
  "        \"name\": \"Submit Delivery Review\",",
  "        \"description\": \"Writes a review of a completed food-delivery order into the restaurant's review section in the delivery app. Only call it when a review genuinely needs to be submitted.\",",
  "        \"visibility\": \"shared\",",
  "        \"handler\": \"submitTakeoutReview\",",
  "        \"parameterSchema\": {",
  "          \"type\": \"object\",",
  "          \"properties\": {",
  "            \"orderId\": { \"type\": \"string\", \"description\": \"Order ID\" },",
  "            \"rating\": { \"type\": \"number\", \"description\": \"Rating from 1 to 5 stars\" },",
  "            \"comment\": { \"type\": \"string\", \"description\": \"The review text written by the character\" }",
  "          },",
  "          \"required\": [\"orderId\", \"rating\", \"comment\"]",
  "        }",
  "      }",
  "    ]",
  "  }",
  "}",
  "```",
  "",
  "Registering the handler when the app code loads:",
  "",
  "```js",
  "AiPhone.tools.handle(\"submitTakeoutReview\", async (args, context) => {",
  "  const review = await AiPhone.db.create(\"reviews\", {",
  "    orderId: args.orderId,",
  "    rating: args.rating,",
  "    comment: args.comment,",
  "    characterId: context.characterId || \"\",",
  "    createdAt: new Date().toISOString()",
  "  });",
  "",
  "  return {",
  "    success: true,",
  "    data: {",
  "      reviewId: review.id,",
  "      orderId: args.orderId,",
  "      rating: args.rating,",
  "      comment: args.comment",
  "    },",
  "    userNotice: \"Delivery review submitted\"",
  "  };",
  "});",
  "```",
  "",
  "The handler's return value enters this turn's generation context as the tool result. Do not write extra chat history inside the handler unless the whole point of the tool is to send a visible message or card into the chat.",
  "",
  "The app can also call tools visible to it directly. This is the app code invoking a tool on its own, without the character deciding to:",
  "",
  "```js",
  "const result = await AiPhone.tools.invoke(\"Submit Delivery Review\", {",
  "  orderId: \"order_123\",",
  "  rating: 5,",
  "  comment: \"Tasted great, and the packaging was careful too.\"",
  "});",
  "```",
  "",
  "To let the character call tools in one of your app's generation scenarios, add a `{{tools}}` entry to `presets.json` that this generation's `appTags` will match. The character only sees the toolbox once that preset enters the prompt.",
  "",
  "```json",
  "[",
  "  {",
  "    \"id\": \"waimai-review-tools\",",
  "    \"name\": \"Delivery Review Tools\",",
  "    \"role\": \"system\",",
  "    \"content\": \"{{tools}}\",",
  "    \"tags\": [\"waimai\", \"review\"],",
  "    \"enabled\": true",
  "  }",
  "]",
  "```",
  "",
  "```js",
  "const result = await AiPhone.ai.generate({",
  "  characterId: selectedCharacterId,",
  "  appTags: [\"waimai\", \"review\"],",
  "  instruction: \"Based on the recent orders and the chat context, decide whether a delivery review should be submitted.\"",
  "});",
  "```",
  "",
  "Tool names, descriptions, and parameter schemas come from the manifest's `extensions.tools`. When the bound API uses text-protocol tools, `{{tools}}` expands into the tool descriptions; when it uses native tools, `{{tools}}` does not expand into text and the real tool schema is sent with the request in the API's native format. If you only want the character to write some review text, you do not need a tool; only call a tool when the review actually has to be written into the delivery app's data.",
  "",
  "### 5.12 Sending App Cards to the Chat",
  "",
  "```js",
  "const [character, userProfile] = await Promise.all([",
  "  AiPhone.characters.get(selectedCharacterId),",
  "  AiPhone.user.getProfile({ characterId: selectedCharacterId })",
  "]);",
  "const characterName = character?.name || \"them\";",
  "const userName = userProfile?.name || \"you\";",
  "",
  "await AiPhone.chat.sendCard({",
  "  characterId: selectedCharacterId,",
  "  role: \"user\",",
  "  summary: `${userName} ordered delivery for ${characterName}: tom yum soup and coconut rice, arriving in about 35 minutes.`,",
  "  historyText: `[Delivery: ${userName} ordered food for ${characterName}; items: tom yum soup, coconut rice; estimated arrival in 35 minutes.]`,",
  "  historyRole: \"user\",",
  "  card: {",
  "    appLabel: \"Float Delivery\",",
  "    title: \"Order Submitted\",",
  "    subtitle: \"ORDER CARD\",",
  "    status: \"Out for delivery\",",
  "    accentColor: \"#f97316\",",
  "    sections: [",
  "      { title: \"Items\", rows: [",
  "        { label: \"Tom Yum Soup\", value: \"x1 · ¥38\" },",
  "        { label: \"Coconut Rice\", value: \"x1 · ¥12\" }",
  "      ] },",
  "      { title: \"Delivery\", rows: [",
  "        { label: \"Recipient\", value: characterName },",
  "        { label: \"ETA\", value: \"35 minutes\" },",
  "        { label: \"Order No.\", value: \"W-1028\" }",
  "      ] }",
  "    ],",
  "    actions: [{ label: \"View Order\" }]",
  "  }",
  "});",
  "```",
  "",
  "`role` controls where the card appears in the chat and can be `user`/`assistant`/`system`. `card` controls the layout the user sees; structure it with fields like status, number, source, and line items, the way the shopping app's gift card does. `historyText` is the chat history text the AI can see; when omitted, `summary`/`card.body` is used instead. Prefer real display names when writing history - the example above fetches the character name and the user's nickname via `characters.get` and `user.getProfile` before interpolating them, so the AI never sees placeholder words like \"the user\" or \"the character\" later in the story. `historyRole` controls the role `historyText` takes in the AI history; when omitted, it follows `role`. For example, a card the character sends on its own initiative can use `role: \"assistant\"` with `historyRole: \"system\"`, so the UI looks like the character sent the card while the prompt records it purely as a fact. Needs `chat.sendCard`, `characters.read`, and `user.profile.read`.",
  "",
  "> `card.actions` only renders buttons. Tapping the card or a button opens the app; the real confirmation, payment, and data writes happen on a page inside the app. If you then want to change the original card from \"Pending\" to \"Confirmed\", use `AiPhone.chat.updateCard`.",
  "",
  "When the app is opened from a chat card, `launchContext` carries `messageId` and `sessionId`. After confirming, you can update the original card:",
  "",
  "```js",
  "const launchContext = await AiPhone.app.getLaunchContext();",
  "await AiPhone.chat.updateCard({",
  "  messageId: launchContext.messageId,",
  "  sessionId: launchContext.sessionId,",
  "  status: \"Confirmed\",",
  "  openDisabled: true,",
  "  actions: [{ label: \"Confirmed\", style: \"muted\", disabled: true }]",
  "});",
  "```",
  "",
  "**Cards are not a fixed template.** The `card` structure above is rendered by the host; if you need a completely different look, you can pass a **static HTML card**. The host displays it in a sandboxed iframe and does not execute scripts:",
  "",
  "```js",
  "const [character, userProfile] = await Promise.all([",
  "  AiPhone.characters.get(selectedCharacterId),",
  "  AiPhone.user.getProfile({ characterId: selectedCharacterId })",
  "]);",
  "const characterName = character?.name || \"them\";",
  "const userName = userProfile?.name || \"you\";",
  "",
  "await AiPhone.chat.sendCard({",
  "  characterId: selectedCharacterId, role: \"user\",",
  "  summary: `Receipt for the delivery ${userName} ordered for ${characterName}: tom yum soup, coconut rice, arriving in about 35 minutes.`,",
  "  historyText: `[Delivery: ${userName} ordered food for ${characterName} and got a receipt; items: tom yum soup, coconut rice; estimated arrival in 35 minutes.]`,",
  "  card: {",
  "    height: 260,",
  "    html: `",
  "      <style>",
  "        .receipt { min-height:260px; padding:18px; color:#2f241c;",
  "          background:#fffaf0; border:1px solid rgba(95,62,35,.16);",
  "          font:14px/1.7 -apple-system,BlinkMacSystemFont,sans-serif; }",
  "        .total { margin-top:12px; border-top:1px dashed #c9a36a; padding-top:10px; font-weight:700; }",
  "      </style>",
  "      <div class=\"receipt\">",
  "        <h3>Float Delivery Receipt</h3>",
  "        <p>Tom Yum Soup x1 · ¥38</p>",
  "        <p>Coconut Rice x1 · ¥12</p>",
  "        <p class=\"total\">Estimated arrival in 35 minutes</p>",
  "      </div>`",
  "  }",
  "});",
  "```",
  "",
  "> An HTML card is display only. To change status, take payment, send a notification, or get a character reply, still use the corresponding SDK APIs.",
  "",
  "### 5.13 Making Chat Aware of App Events",
  "",
  "When you only want the character to know something happened and do not need a card, use `chat.writeHistory`:",
  "",
  "```js",
  "const userProfile = await AiPhone.user.getProfile({ characterId: selectedCharacterId });",
  "const userName = userProfile?.name || \"you\";",
  "",
  "await AiPhone.chat.writeHistory({",
  "  characterId: selectedCharacterId, role: \"user\",",
  "  content: `[CheckIn: ${userName} completed today's morning check-in and is feeling good.]`",
  "});",
  "```",
  "",
  "Needs `chat.write` or `chat.sendMessage`; if you read the user's nickname as in the example above, it also needs `user.profile.read`.",
  "",
  "> Custom apps **cannot** use system directives or silent context injection. To make the AI aware of an event, write a normal history message or send an app card with `historyText`.",
  "",
  "### 5.14 Requesting a Character Reply in the Chat",
  "",
  "Recommended flow: first write the app event into the real chat history with `chat.writeHistory` or `chat.sendCard`, then request a reply through the normal chat pipeline.",
  "",
  "```js",
  "const userProfile = await AiPhone.user.getProfile({ characterId: selectedCharacterId });",
  "const userName = userProfile?.name || \"you\";",
  "",
  "await AiPhone.chat.writeHistory({",
  "  characterId: selectedCharacterId,",
  "  role: \"user\",",
  "  content: `[CheckIn: ${userName} completed today's morning check-in and is feeling good.]`",
  "});",
  "",
  "await AiPhone.chat.requestReply({",
  "  characterId: selectedCharacterId",
  "});",
  "```",
  "",
  "Needs `chat.requestReply`. `requestReply` triggers an ordinary chat reply, identical to the generation pipeline used when the user sends a message from the chat box; it does not accept app scenario tags and does not load app-specific presets. What the character sees is the history message or card `historyText` you just wrote. If you read the user's nickname as in the example above, it also needs `user.profile.read`.",
  "",
  "If the app needs to generate content with its own app presets, call `AiPhone.ai.generate` and then write the result back into the chat with `chat.writeHistory` or `chat.sendCard`.",
  "",
  "### 5.15 Opening a Character's Chat",
  "",
  "```js",
  "await AiPhone.chat.openConversation({ characterId: selectedCharacterId });",
  "```",
  "",
  "### 5.16 Changing Chat Contact State",
  "",
  "Lets you build apps that hook into chat features like blocking and do-not-disturb:",
  "",
  "```js",
  "await AiPhone.chat.setContactState({",
  "  characterId: selectedCharacterId, isBlacklisted: true, isMuted: true",
  "});",
  "await AiPhone.chat.unblock(selectedCharacterId);",
  "await AiPhone.chat.unmute(selectedCharacterId);",
  "```",
  "",
  "Needs `chat.contacts.write`.",
  "",
  "### 5.17 Reading Chat History",
  "",
  "```js",
  "const current = await AiPhone.chat.getCurrentSession();",
  "const history = await AiPhone.chat.readHistory({ sessionId: current?.sessionId, limit: 30 });",
  "```",
  "",
  "Needs `chat.read`. `getCurrentSession` returns session info **only when the app was opened from a chat card or the plus panel**; it is `null` when the app is opened directly from the home screen. So never assume you can get the current session - under the home-screen entry point, the user should pick `sessionId`/`characterId` inside the app themselves (for example by using `characters.list` to let them choose a character first).",
  "",
  "### 5.18 Listening to Chat Events",
  "",
  "You can listen to events declared in the manifest's `extensions.events`. Currently `chat.message.created` is supported, for reacting to new messages from the user or the character. When the event declaration sets `background: true`, the host temporarily starts a hidden runtime even if the app is closed, runs the same `AiPhone.on` handler, and destroys it afterwards. The hidden runtime is kept for at most 5 minutes by default; if you genuinely need longer, set `timeoutMs` in the event declaration, up to a maximum of 30 minutes.",
  "",
  "```js",
  "const stop = AiPhone.on(\"chat.message.created\", async (payload) => {",
  "  const text = payload.message?.content || \"\";",
  "  if (payload.message?.role !== \"assistant\") return;",
  "  if (!text.includes(\"[DriftBottle:\")) return;",
  "",
  "  await AiPhone.db.create(\"bottles\", {",
  "    content: text,",
  "    characterId: payload.characterId,",
  "    messageId: payload.message.id,",
  "    createdAt: new Date().toISOString()",
  "  });",
  "});",
  "// When you no longer need it:",
  "stop();",
  "```",
  "",
  "You must declare the event in `extensions.events` and request the `chat.read` or `chat.read.background` permission. Async operations inside a background handler must be `await`ed or returned as a Promise - the host waits for the Promise to settle; if you merely kick off an async task without returning a Promise, the hidden runtime may be destroyed early. Chat messages written by a background handler carry the `custom_app_background` source, and the host will not use those messages to trigger background listeners again, which prevents infinite loops.",
  "",
  "### 5.19 Reading Memory",
  "",
  "```js",
  "const core = await AiPhone.memory.readCore({ characterId: selectedCharacterId });",
  "const longTerm = await AiPhone.memory.readLongTerm({ characterId: selectedCharacterId, query: \"mild flavors\" });",
  "const shortTerm = await AiPhone.memory.readShortTerm({ characterId: selectedCharacterId, limit: 30 });",
  "const found = await AiPhone.memory.search({ characterId: selectedCharacterId, query: \"prefers less spice\" });",
  "```",
  "",
  "These need `memory.readCore` / `memory.readLongTerm` / `memory.readShortTerm` / `memory.search` respectively.",
  "",
  "### 5.20 Writing Memory",
  "",
  "Three ways to write, chosen by how important the memory is:",
  "",
  "**`memory.add`** - writes long-term/core memory. **Use it only when something is genuinely important and should influence the character over the long run.** Do not turn every click into a long-term memory.",
  "",
  "```js",
  "const userProfile = await AiPhone.user.getProfile({ characterId: selectedCharacterId });",
  "const userName = userProfile?.name || \"you\";",
  "",
  "await AiPhone.memory.add({",
  "  characterId: selectedCharacterId, type: \"long_term\",",
  "  content: `${userName} has a long-standing preference for mild, low-spice food.`,",
  "  importance: 0.6, reason: \"Observed across repeated orders in the delivery app\"",
  "});",
  "```",
  "",
  "Needs `memory.write`; if you read the user's nickname as in the example above, it also needs `user.profile.read`.",
  "",
  "**`memory.suggest`** - only proposes a memory, to be confirmed later by the user or the host. **It does not write into long-term memory directly.**",
  "",
  "```js",
  "const userProfile = await AiPhone.user.getProfile({ characterId: selectedCharacterId });",
  "const userName = userProfile?.name || \"you\";",
  "",
  "await AiPhone.memory.suggest({",
  "  characterId: selectedCharacterId, type: \"long_term\",",
  "  content: `${userName} likes mild, low-spice delivery food.`, reason: \"Observed across repeated orders\"",
  "});",
  "```",
  "",
  "Needs `memory.suggest`; if you read the user's nickname as in the example above, it also needs `user.profile.read`.",
  "",
  "**`memory.addTimeline`** - writes a custom app event into that character's global short-term memory event stream. Once written, every app operating on the same character will read this event from the short-term memory event stream during `AiPhone.ai.generate`.",
  "",
  "Note: `chat.sendCard({ historyText })` and `chat.writeHistory` are part of the chat history, so they also enter the short-term memory event stream. If you already wrote the same event with `chat.sendCard` or `chat.writeHistory`, there is no need to call `memory.addTimeline` again for it.",
  "",
  "```js",
  "const [character, userProfile] = await Promise.all([",
  "  AiPhone.characters.get(selectedCharacterId),",
  "  AiPhone.user.getProfile({ characterId: selectedCharacterId })",
  "]);",
  "const characterName = character?.name || \"them\";",
  "const userName = userProfile?.name || \"you\";",
  "",
  "const timeline = await AiPhone.memory.addTimeline({",
  "  characterId: selectedCharacterId, appLabel: \"Float Delivery\",",
  "  detail: \"order_delivered\", summary: `The tom yum soup and coconut rice ${userName} ordered for ${characterName} have arrived.`,",
  "  appEventId: \"order_001\",",
  "  data: { orderId: \"order_001\" }",
  "});",
  "```",
  "",
  "If the event is later undone, the order is cancelled, or the user deletes the corresponding card, you can delete the short-term timeline entries by the same `appEventId`. To delete just one entry, use the `entry.id` returned by `addTimeline`:",
  "",
  "```js",
  "await AiPhone.memory.deleteTimeline({",
  "  characterId: selectedCharacterId,",
  "  appEventId: \"order_001\"",
  "});",
  "",
  "await AiPhone.memory.deleteTimeline({ entryId: timeline.entry.id });",
  "```",
  "",
  "`addTimeline` / `deleteTimeline` both need `memory.write`; if you read the character name and the user's nickname as in the example above, they also need `characters.read` and `user.profile.read`.",
  "",
  "### 5.21 UI Prompts",
  "",
  "```js",
  "await AiPhone.ui.toast(\"Saved\");",
  "await AiPhone.ui.showNotification({ title: \"Float Delivery\", body: \"Order status updated.\" });",
  "const ok = await AiPhone.ui.confirm({ title: \"Delete this?\", message: \"This cannot be undone.\" });",
  "```",
  "",
  "`toast` needs `ui.toast`, `showNotification` needs `ui.notification`, and `confirm` needs no special permission.",
  "",
  "### 5.22 Notifications and Home Screen Badges",
  "",
  "```js",
  "await AiPhone.notifications.create({",
  "  title: \"Delivery Arrived\", body: \"Your tom yum soup and coconut rice are at the door.\",",
  "  badgeDelta: 1, data: { orderId: \"order_001\" }",
  "});",
  "const badge = await AiPhone.notifications.getBadge();",
  "await AiPhone.notifications.setBadge(badge + 1);",
  "await AiPhone.notifications.clearBadge();",
  "const notices = await AiPhone.notifications.list({ unreadOnly: true });",
  "await AiPhone.notifications.markAllRead();",
  "```",
  "",
  "Needs `notifications.read` / `notifications.write`.",
  "",
  "### 5.23 Background Scheduled Tasks",
  "",
  "Good for delayed actions like \"delivery estimated to arrive\" or \"remind me to check in tomorrow\". Tasks do not actually run while the browser is closed, but once the user reopens the phone, **any tasks that came due are run to catch up**.",
  "",
  "```js",
  "const [character, userProfile] = await Promise.all([",
  "  AiPhone.characters.get(selectedCharacterId),",
  "  AiPhone.user.getProfile({ characterId: selectedCharacterId })",
  "]);",
  "const characterName = character?.name || \"them\";",
  "const userName = userProfile?.name || \"you\";",
  "",
  "await AiPhone.tasks.schedule({",
  "  id: \"order_001_delivered\",",
  "  delayMs: 35 * 60 * 1000,",
  "  actions: [",
  "    { type: \"notification\", title: \"Your Food Is Here\", body: \"Your tom yum soup has arrived.\", badgeDelta: 1 },",
  "    { type: \"chat.card\", characterId: selectedCharacterId,",
  "      role: \"user\", historyRole: \"user\",",
  "      title: \"Delivery Arrived\", body: \"The tom yum soup and coconut rice are at the door.\",",
  "      historyText: `[Delivery: the tom yum soup and coconut rice ${userName} ordered for ${characterName} have arrived]` },",
  "    { type: \"chat.reply\", characterId: selectedCharacterId }",
  "  ]",
  "});",
  "```",
  "",
  "Needs `tasks.schedule` plus the permissions each action itself requires; if you read the character name and the user's nickname as in the example above, it also needs `characters.read` and `user.profile.read`.",
  "",
  "> In a background task, **every action is independent and does not inherit the outer `appTags`**. `chat.reply` only triggers an ordinary chat reply; if you need app scenario presets, generate the content inside the task with your app's own `AiPhone.ai.generate` first, then write it into the chat history or a card.",
  "",
  "**Available action types**: `notification`, `badge`, `chat.card`, `chat.history`, `chat.message`, `chat.reply`, `memory.add`, `memory.timeline`, `memory.deleteTimeline`, `memory.suggest`, `wallet.pay`, `chat.contact`, `calendar.write`.",
  "",
  "**Action field quick reference**:",
  "",
  "|type|Fields|",
  "|-|-|",
  "|`notification` / `ui.notification`|`title`, `body`, `badgeDelta`, `data`|",
  "|`badge` / `notifications.badge`|`count` or `delta`|",
  "|`chat.card`|`characterId`, `role`, `historyRole`, `title`, `body`, `summary`, `historyText`, `card`|",
  "|`chat.history` / `chat.message`|`characterId`, `role`, `content`|",
  "|`chat.reply`|`characterId`, `context`. `context` is first written as a `user` history message; if a previous step already wrote the event with `chat.card` or `chat.history`, do not pass `context` again|",
  "|`memory.add`|`characterId`, `content`, `type`, `importance`, `reason`|",
  "|`memory.timeline` / `memory.addTimeline`|`characterId`, `summary`, `detail`, `appLabel`, `appEventId`, `data`, `createdAt`|",
  "|`memory.deleteTimeline` / `memory.removeTimeline`|`entryId`, or `characterId` + `appEventId`|",
  "|`memory.suggest`|`characterId`, `content`, `type`, `importance`, `reason`|",
  "|`wallet.pay`|`amount`, `accountId`, `title`, `detail`, `category`, `relatedOrderId`|",
  "|`calendar.write`|`date`, `startTime`, `endTime`, `title`, `ownerType/ownerId/characterId`; `operation` can also be passed|",
  "",
  "### 5.24 Wallet Payments",
  "",
  "Delivery, ticketing, and service apps can charge the user's wallet:",
  "",
  "```js",
  "const wallet = await AiPhone.wallet.get();",
  "const result = await AiPhone.wallet.pay({",
  "  amount: 50, accountId: wallet.accounts[0].id,",
  "  title: \"Float Delivery\", detail: \"Tom yum soup, coconut rice\",",
  "  category: \"delivery\", relatedOrderId: \"order_001\"",
  "});",
  "if (!result.ok) await AiPhone.ui.toast(result.error || \"Payment failed\");",
  "```",
  "",
  "Needs `wallet.read` / `wallet.pay`.",
  "",
  "### 5.25 Multiplayer (Realtime Rooms + Cloud Sharing)",
  "",
  "Apps can connect **real people using different accounts**: open a room for realtime play or chat, or use cloud-shared data for asynchronous formats like drift bottles and leaderboards. You must declare the `online.play` permission. Multiplayer is only available on sites where the user **is signed in to a multiplayer account** (standalone mode has no account system, so calls will throw - catch them and tell the user).",
  "",
  "Two sets of primitives; pick by the kind of experience you want:",
  "",
  "|Format|Which layer|Examples|",
  "|-|-|-|",
  "|Several people online at once, messages arrive instantly|Realtime rooms `AiPhone.room.*`|Werewolf, Spyfall, Pictionary, chat rooms|",
  "|Players do not need to be online together; relies on a shared data pool|Cloud sharing `AiPhone.cloud.*`|Drift bottles, leaderboards, message boards, browsing other people's shops|",
  "",
  "#### Realtime Rooms",
  "",
  "```js",
  "// Host opens a room (returns a 4-character code to show friends)",
  "const room = await AiPhone.room.create({ title: \"Werewolf\", maxPlayers: 8 });",
  "showCode(room.code);            // e.g. \"8A3F\"; room.selfUserId is your own multiplayer identity",
  "",
  "// Other players join with the code",
  "const joined = await AiPhone.room.join({ code: \"8A3F\" });",
  "",
  "// Send and receive messages (delivered to everyone else in the room; your own messages do not echo back)",
  "AiPhone.on(\"room.message\", (msg) => { render(msg.from.name, msg.payload); });",
  "await AiPhone.room.send({ type: \"chat\", text: \"Hi everyone\" });",
  "",
  "// Players joining and leaving (presence is maintained automatically)",
  "AiPhone.on(\"room.players\", ({ players }) => renderPlayerList(players));",
  "",
  "// Authoritative state: only the host can write it, and everyone (including late joiners) automatically receives the latest copy",
  "AiPhone.on(\"room.state\", ({ state }) => renderGame(state));",
  "if (room.isHost) await AiPhone.room.setState({ phase: \"night\", round: 1 });",
  "",
  "// Host privileges and leaving",
  "await AiPhone.room.kick(playerId);   // kick a player (they are removed and cannot rejoin)",
  "await AiPhone.room.close();          // close the room",
  "await AiPhone.room.leave();          // a regular player leaves",
  "AiPhone.on(\"room.closed\", ({ reason }) => showEnd(reason)); // host_closed / host_left / kicked",
  "```",
  "",
  "**Room events must be declared in the manifest's `extensions.events`** (`room.message`, `room.players`, `room.state`, `room.closed` - declare the ones you use), then listened to with `AiPhone.on`.",
  "",
  "**Architecture rules (important - following them avoids 90% of multiplayer bugs)**:",
  "",
  "* **Keep authoritative logic on the host side**: the secret word in Spyfall, role assignment in Werewolf, round adjudication - all of it is computed by the host's client and pushed out with `room.setState`. Other players only report their own actions to the host with `room.send`. Do not let every client compute its own version.",
  "* **Always render the game from `room.state`** - a new player entering the room automatically receives the latest state, and a reconnecting player recovers too. Treat `room.send` messages as \"events\", never as \"state\".",
  "* If the host drops for 30 seconds, the room ends automatically (everyone receives `room.closed` with reason `host_left`), so build a proper wrap-up UI. Host migration is not supported in this version.",
  "* An app has only one room connection at a time; closing the app leaves the room automatically (host closes the app = room closes).",
  "* Rate limits: 25 messages per person per second, 16000 characters per message. **Batch up** Pictionary strokes (for example, one batch of coordinates every 100ms).",
  "* Suited to turn-based play and low-frequency syncing (mobile network latency is 200-500ms); **not suited** to frame-synced action games. The host is an ordinary client with limited anti-cheat ability, so do not build high-stakes competitive rankings on it.",
  "",
  "#### Bringing Characters to the Table (Humans and AI Characters Playing Together)",
  "",
  "Multiplayer is not only human versus human: each player can also bring **their own character** into the room (for example, two users plus their respective characters make up a table of Werewolf). The core principle: **a character is driven by its owner's client** - the persona, memory, and API key all live only on the owner's device. When it is the character's turn to act, the owner's client calls `ai.generate` locally (passing `characterId`, so the host assembles the full persona automatically) and sends the result out with `room.send` as if it were an ordinary player action. Other players only ever see what the character says and never obtain its persona; tokens are consumed by the character's owner. Requires the `ai.generate` and `characters.read` permissions.",
  "",
  "```js",
  "// After joining, report the character you brought to the host; the host records it as a virtual seat in state:",
  "// state.seats = [{ seatId, kind: \"human\"|\"character\", ownerUserId, name, charId }], state.turn = seatId",
  "await AiPhone.room.send({ type: \"bring\", name: \"Xiaohong\", charId: chosenId });",
  "",
  "// Every client receives state: when it is the turn of \"a character seat I own\", act on its behalf",
  "AiPhone.on(\"room.state\", async ({ state }) => {",
  "  const seat = state.seats.find(s => s.seatId === state.turn);",
  "  if (seat && seat.kind === \"character\" && seat.ownerUserId === me.userId && !generating) {",
  "    generating = true;",
  "    const result = await AiPhone.ai.generate({",
  "      characterId: seat.charId,",
  "      instruction: `You are playing Werewolf. Current situation: ${describe(state)}. Speak in character (under 60 words, output only the speech).`,",
  "    });",
  "    await AiPhone.room.send({ type: \"action\", seatId: seat.seatId, text: result.text });",
  "    generating = false;",
  "  }",
  "});",
  "```",
  "",
  "Do not confuse the two kinds of AI participant: **characters brought by players** (the case above) are driven by their respective owners' clients, while **ownerless NPCs** (a system referee, a filler player) have no owner and are generated entirely on the host side and written into state. Two more things to handle: if a character's owner drops, the turn will stall, so implement a timeout skip on the host side (auto-pass after 60 seconds with no response), and take a lock during generation to prevent duplicate triggers.",
  "",
  "#### Cloud Sharing (Asynchronous Play)",
  "",
  "```js",
  "// Drift bottles: throw one / pick up a random one from someone else (picking it up claims it exclusively, so two people never get the same bottle)",
  "await AiPhone.cloud.put({ collection: \"bottles\", data: { text: \"Anyone out there?\" } });",
  "const bottle = await AiPhone.cloud.takeRandom({ collection: \"bottles\" });",
  "if (bottle) show(bottle.ownerName, bottle.data.text);   // may be null (the pool is empty)",
  "",
  "// Leaderboard: sort by sortKey and take the top N",
  "await AiPhone.cloud.put({ collection: \"scores\", data: { score: 9800 }, sortKey: 9800 });",
  "const top = await AiPhone.cloud.list({ collection: \"scores\", orderBy: \"sortKey\", limit: 10 });",
  "",
  "// Your own data: list / update / delete (you can only touch your own)",
  "const mine = await AiPhone.cloud.list({ collection: \"bottles\", mine: true });",
  "await AiPhone.cloud.update({ id: mine[0].id, data: { text: \"edited\" } });",
  "await AiPhone.cloud.delete(mine[0].id);",
  "```",
  "",
  "Rules: data is isolated per app (you cannot read other apps' data); each `data` is capped at 8000 characters; each user may hold at most 200 documents in this app; `list` returns at most 50 per call. Every document carries `ownerId` / `ownerName` / `createdAt`.",
  "",
  "> Content safety reminder: both multiplayer rooms and cloud sharing are person-to-person channels. The host provides built-in reporting: `AiPhone.cloud.report({ id, reason })` reports a piece of cloud content (such as a drift bottle you picked up), and `AiPhone.room.report(reason)` reports the current room. Put report buttons in the corresponding UI (hosts use `kick` to remove players), and do not build formats that encourage strangers to privately exchange personal information.",
  "",
  "---",
  "",
  "## 6. Permission List",
  "",
  "In `permissions`, declare only the capabilities you actually use.",
  "",
  "### 6.1 Common",
  "",
  "* `app.data.read` / `app.data.write`: read and write this app's private data.",
  "* `app.assets.read`: read resources bundled with this app.",
  "* `app.manifest.read`: read the manifest and the SDK capability summary.",
  "* `characters.read`: read basic character information.",
  "* `ai.generate`: have a specified character generate content for an app task, without posting it to the chat automatically.",
  "* `chat.read`: read chat sessions and history within the authorized scope.",
  "* `chat.read.background`: listen for chat messages in the background while the app is closed; also usable when a background handler needs to read chat history.",
  "* `chat.write` / `chat.sendMessage`: send ordinary chat messages, or write app event history via `chat.history`.",
  "* `chat.sendCard`: send an app card into a character's chat.",
  "* `chat.requestReply`: ask a character to reply in the chat based on the history or app card already written.",
  "* `ui.toast`: show a brief toast.",
  "* `ui.notification`: show a notification.",
  "",
  "### 6.2 Characters / User / Memory",
  "",
  "* `characters.state.read` / `characters.state.write`: read and write character state.",
  "* `characters.relations.read`: read character relationships.",
  "* `user.profile.read` / `user.persona.read` / `user.preferences.read`: read the user's profile, persona, and preferences.",
  "* `memory.readCore` / `memory.readLongTerm` / `memory.readShortTerm` / `memory.search`: read or search memory.",
  "* `memory.write`: write character memory.",
  "* `memory.suggest`: submit a suggested memory write.",
  "",
  "### 6.3 Advanced Capabilities",
  "",
  "* `ai.chat` / `ai.embed` / `ai.classify`: advanced AI conversation, embeddings, and classification.",
  "* `ai.generateImage`: generate an image using the image-generation API already configured in the host.",
  "* `network.fetch`: reach the domains declared in the manifest's `network.allowedDomains`.",
  "* `voice.tts` / `voice.stt` / `voice.clone` / `voice.readProfiles`: speech synthesis, recognition, cloning, and reading voice configurations.",
  "* `chat.contacts.write`: change contact state (block, unblock, do not disturb).",
  "* `chat.tools`: register tools the AI can call.",
  "* `world.read`: read world books.",
  "* `calendar.read` / `calendar.write`: read and write the calendar.",
  "* `media.pick` / `media.save`: pick or save media.",
  "* `media.put` / `media.get` / `media.delete`: the media store - audio and images are stored as Blobs in exchange for a reference, and db records hold only the reference.",
  "* `voice.play` / `voice.stopPlayback` / `voice.pausePlayback` / `voice.resumePlayback`: delegate audio playback to the host (required on iOS, see 5.9).",
  "* `notifications.read` / `notifications.write`: read this app's notifications and badge / create notifications and set the home screen badge.",
  "* `tasks.schedule`: create background scheduled tasks (they do not run while the browser is closed, and due tasks are caught up on reopening).",
  "* `wallet.read` / `wallet.pay`: read the wallet balance and available payment accounts / charge the user's wallet.",
  "* `online.play`: multiplayer - realtime rooms and cloud-shared data (see 5.25).",
  "",
  "---",
  "",
  "## 7. Frontend Requirements",
  "",
  "1. Output HTML/CSS/JS that **runs as-is**, with no npm install or build tooling required from the user.",
  "2. The page runs in a phone-sized iframe, so it must work in **portrait orientation with touch** input.",
  "3. The host floats a translucent system back capsule in the **top-right corner** (tapping it returns to the home screen). **Do not put important buttons in the top-right corner** or they will overlap; the top-left is fine for your own title or back control.",
  "4. When there is a lot of content, build a scrolling region inside the app and avoid horizontal scrolling.",
  "5. Do not use remote scripts that require cross-origin permissions; put images, fonts, and CSS in `assets/`.",
  "",
  "Using the safe-area variables is recommended:",
  "",
  "```css",
  "html, body {",
  "  width: 100%;",
  "  min-height: 100%;",
  "  margin: 0;",
  "}",
  "* { box-sizing: border-box; }",
  ".app {",
  "  min-height: 100dvh;",
  "  padding: var(--ai-phone-app-safe-top, 88px) 16px var(--ai-phone-app-safe-bottom, 24px);",
  "}",
  "button, input, textarea { font: inherit; }",
  "button { min-height: 44px; }",
  "```",
  "",
  "---",
  "",
  "## 8. Implementation Workflow and a Prompt Template for AI",
  "",
  "### 8.1 Recommended Workflow",
  "",
  "1. Build a single-HTML prototype first and get the UI and interactions working.",
  "2. Then add `manifest.json` and `icon.png`.",
  "3. Declare only the permissions you genuinely use.",
  "4. Add `presets.json` when you need deep integration with the chat.",
  "5. Have the user test locally first and confirm that app cards, chat awareness, and memory writes all behave as expected before publishing to the market.",
  "",
  "### 8.2 How to Phrase Your Request When Asking an AI to Build the App",
  "",
  "> Please generate a complete custom app package for the AI Phone app market, following the SDK and file structure above. My app idea is:",
  ">",
  "> [describe your idea here]",
  ">",
  "> Please output the contents of every file, including at minimum manifest.json, index.html, and a design suggestion for icon.png. If scenario presets are needed, output presets.json as well. index.html must run as-is, the UI must fit a phone in portrait orientation, and all SDK calls must go through window.AiPhone.",
  "",
];

export const CUSTOM_APP_CREATOR_GUIDE_MD = CUSTOM_APP_CREATOR_GUIDE_LINES.join("\n");
