"use client";

import { Info, ShieldAlert, Heart } from "lucide-react";

export function AboutDeclaration() {
    return (
        <div className="flex flex-col gap-5 h-full">
            <p className="card-section-label m-0 mx-2">Disclaimer</p>

            <div className="g-card">
                <div className="flex items-start gap-3">
                    <ShieldAlert size={20} className="shrink-0 mt-0.5 text-[var(--c-warning)]" />
                    <div className="flex flex-col gap-2">
                        <span className="menu-label font-semibold">AI-Generated Content Disclaimer</span>
                        <span className="menu-desc ts-13 leading-relaxed !mt-0">
                            All character dialogue and dynamic content in this app is automatically generated by AI models. The generated content does not represent the views or positions of this platform, nor does it correspond to any real people or events. Users should exercise their own judgment and assume the risks of use.
                        </span>
                    </div>
                </div>
                <div className="ui-row-divider !mx-0" />
                <div className="flex items-start gap-3">
                    <Info size={20} className="shrink-0 mt-0.5 text-[var(--c-icon-active)]" />
                    <div className="flex flex-col gap-2">
                        <span className="menu-label font-semibold">Privacy & Data Security</span>
                        <span className="menu-desc ts-13 leading-relaxed !mt-0">
                            Sensitive data such as your diary entries, chat history, and persona presets is stored locally in your browser by default (LocalStorage/IndexedDB). Clearing your browser cache may cause data loss, so please back it up properly.
                        </span>
                    </div>
                </div>
            </div>

            <p className="card-section-label m-0 mx-2">Related Information</p>

            <div className="flex flex-col gap-2">
                <button className="g-card flex-row items-center">
                    <Heart size={20} fill="currentColor" className="shrink-0 text-[var(--c-icon-rose)]" />
                    <span className="menu-label flex-1">Support the Developer</span>
                    <span className="menu-desc !mt-0">Buy me a coffee</span>
                </button>
            </div>

        </div>
    );
}
