-- D1 schema for the Proactive Message 2.0 Worker.
-- See PROACTIVE-MESSAGE-2.0-PLAN.md at the repo root for the full design.
-- Idempotent (IF NOT EXISTS) so re-running the one-click deploy never fails
-- or destroys existing data.

CREATE TABLE IF NOT EXISTS subscriptions (
    id TEXT PRIMARY KEY,          -- random id, generated by the Worker on insert
    endpoint TEXT NOT NULL UNIQUE,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    character_id TEXT,            -- NULL in Stage 2 (device-wide test subscription only)
    created_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL
);

-- Stage 3+ tables (created now so the schema only ever needs additive
-- migrations later, never a destructive one):

CREATE TABLE IF NOT EXISTS character_snapshots (
    character_id TEXT PRIMARY KEY,
    snapshot_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS proactive_state (
    character_id TEXT NOT NULL,
    mechanism TEXT NOT NULL,      -- "follow_up" | "timed_wake" | "period_care"
    state_json TEXT NOT NULL,     -- last fired timestamp, cycle key, schedule id, etc.
    updated_at TEXT NOT NULL,
    PRIMARY KEY (character_id, mechanism)
);

CREATE TABLE IF NOT EXISTS pending_messages (
    id TEXT PRIMARY KEY,
    character_id TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TEXT NOT NULL,
    delivered INTEGER NOT NULL DEFAULT 0
);

-- Small key/value table for Worker-wide bookkeeping, e.g. "when did the Cron
-- Trigger last actually run" — used by GET /status so the settings UI can
-- confirm scheduling works without needing the user to inspect Worker logs.
CREATE TABLE IF NOT EXISTS worker_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
